language: python
python:
  - "2.7"
  - "3.6"
notifications:
  email: false
install:
  - "pip install pep8 pylint"
  - "pip install tables scipy"
  # TODO: Move tables, etc. to requirements.txt, specify versions.
script:
  - "pylint --rcfile=.pylintrc --errors-only bamliquidator_internal/"
