#!/usr/bin/env python

# Note this is intended as an example only -- it would almost certainly be much better to just use the
# results in HDF5 instead of CSV since PyTables is much faster and allow much more flexibility than csv. 

# This is intended to match the format of the csvs generated by bam_liquidator_bin_plot_by_cell_type.py
# but has precise decimal averge percentiles (as opposed to integer percentiles). 

import argparse
import csv
import os
import tables

def write_row(writer, row):
    writer.writerow([row["bin_number"], row["avg_cell_type_percentile"],
        row["cell_types_gte_95th_percentile"], row["cell_types_lt_95th_percentile"],
        row["lines_gte_95th_percentile"], row["lines_lt_95th_percentile"],
        row["cell_types_gte_5th_percentile"], row["cell_types_lt_5th_percentile"],
        row["lines_gte_5th_percentile"], row["lines_lt_5th_percentile"]])
    

def write_csv(normalized_counts, chromosome, csv_file_path, ascending_percentile_order):
    with open(csv_file_path, 'wb') as csvfile:
        writer = csv.writer(csvfile)
        header = ["bin","average cell type percentile",
                  "cell types >= 95th percentile" "cell types < 95th percentile",
                  "lines >= 95th percentile", "lines < 95th percentile",
                  "cell types >= 5th percentile", "cell types < 5th percentile",
                  "lines >= 5th percentile", "lines < 5th percentile"] 
        writer.writerow(header)
        
        # iterating efficiently in sorted ascending/descending order has some surprising performance 
        # characteristics, see https://groups.google.com/d/topic/pytables-users/EKMUxghQiPQ/discussion
        if ascending_percentile_order:
            summary = normalized_counts.root.summary
            for row in summary.itersorted(summary.cols.avg_cell_type_percentile, checkCSI=True):
                if row["chromosome"] == chromosome:
                    write_row(writer, row)
        else:
            # sorted in descending percentile order
            sorted_summary = normalized_counts.root.sorted_summary
            for row in sorted_summary.read_where("chromosome == '%s'" % chromosome):
                write_row(writer, row)

def main():
    parser = argparse.ArgumentParser(description='Writes bamliquidator_batch.py hdf5 summary into csv files, '
                                     'one for each chromosome and sorted by percentile order.  This is '
                                     'just an example, and using hdf5 directly instead of csv is preferred.')
    parser.add_argument('normalized_counts_h5_file', help='the hdf5 file with "summary" and "sorted_summary" '
                                                          'tables as generated by bamliquidator_batch.py')
    parser.add_argument('output_directory', help='directory to store the csv files, should already exist')
    parser.add_argument('--ascending_percentile_order', action='store_true',
                        help='writes csv with lowest percentiles first (i.e. the cold spots first) -- default is '
                             'to write in descending percentile order so that the highest percentiles are first'
                             '(i.e. the hot spots first)')
    args = parser.parse_args()

    normalized_counts = tables.open_file(args.normalized_counts_h5_file, mode = "r")
    
    chromosomes = [ 'chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr8', 'chr9', 'chrX',
                    'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17',
                    'chr18', 'chr19', 'chr20', 'chr21', 'chr22' ]

    for chromosome in chromosomes:
        print "Writing " + chromosome
        write_csv(normalized_counts, chromosome, os.path.join(args.output_directory, chromosome + ".csv"),
                  args.ascending_percentile_order)

    normalized_counts.close()

if __name__ == "__main__":
    main()

'''
   The MIT License (MIT) 

   Copyright (c) 2013 John DiMatteo (jdimatteo@gmail.com) 

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE. 
'''
